### ISSUE TITLE
Stitch EPUBs from multiple URLs - add impl

### ISSUE THREAD

**Issue by SphericalKat** [captn3m0/ideas#15]
I whipped up a simple implementation (for https://github.com/captn3m0/ideas#stitch-epubs-from-multiple-urls)  over the weekend: https://github.com/sphericalKat/gopherpress

**Comment by captn3m0** [comment]
Good work! Do [send me your address](https://captnemo.in/contact/) and I can send you your postcard.

Aside: Since cover image is part of the [spec](https://w3c.github.io/epub-specs/epub33/core/#sec-cover-image), might be worth specifying in the metadata.

**Comment by SphericalKat** [comment]
> Aside: Since cover image is part of the [spec](https://w3c.github.io/epub-specs/epub33/core/#sec-cover-image), might be worth specifying in the metadata.
Nice catch! I'll work that into the project

I sent you an email with the subject `SphericalKat - Address` from `me (at) kat.bio`
Cheers
