### ISSUE TITLE
YC's 13 Startup Ideas

### ISSUE THREAD

**Issue by umanghome** [captn3m0/ideas#4]
YC published [this](http://blog.ycombinator.com/13-startup-ideas/) last week and it has a list of startup ideas that they'd like to see.

Is there a section in the doc where links to resources like these can be provided?

**Comment by captn3m0** [comment]
I can create a `SIMILAR.md` file with links to other such posts (Maybe the HN Ideas thread for eg.)

**Comment by umanghome** [comment]
I was thinking a `Similiar` section in README, but anything works. I'll raise a PR. Point me to the HN thread?

**Comment by captn3m0** [comment]
This was the first I think: https://news.ycombinator.com/item?id=7541601. Complete list is at https://hn.algolia.com/?query=%22Ask%20HN:%20Idea%20Sunday%22&sort=byDate&prefix=false&page=0&dateRange=all&type=story

Other sources: http://mib.im/open-source-ideas/, https://github.com/joereynolds/what-to-code

Feel free to add more if you have any recommendations
